### ISSUE TITLE
Format control for pest_io

### ISSUE THREAD

**Issue by porterma** [dharp/matk#1]
Is there an easy way to control/specify the format of parameters written in the pest_io package? I've been dealing with some pretty constrained input files that only work with a specific format for float parameters.

**Comment by dharp** [comment]
Sure, any python formatting will work within the parameter identifier tokens. For example "int()" or "float()" will work. Higher level, you could even use the "format" function to get the float in the exact format you need it in.

**Comment by porterma** [comment]
Sorry for ignorance. Where do I specify the float format of '10.4e' so it writes to my input file for parameters that I have specified with add_par and parstudy? I've looked all over with no luck and forced some pretty bad hacks to make it work.

**Comment by dharp** [comment]
No worries, after a second look, I realize my response was pretty vague. Within the parameter identifier in the TPL file (lets say its the pound sign "#"), you can do:

#"{:.5E}".format(par)#

or you can use the old formatting in python:

#"%.5e"%(par)#

Basically, anything you can do in python, you can do within the parameter identifiers in the TPL file.

For example, I used the following line in a TPL file because the fortran code expected a "D" instead of the "e" in the scientific notation:

#("%g"%10**Dd).replace("e","D")#

**Comment by porterma** [comment]
Thanks, I would have never thought of that. It's working great.

**Comment by dharp** [comment]
Glad it worked!
